version: '3.9'
services:
  us-east:
    environment:
      - REGION=us-east
    build:
      context: .
    ports:
      - "50000:5000"

  eu-north:
    environment:
      - REGION=eu-north
    build:
      context: .
    ports:
      - "50001:5000"

  ap-south:
    environment:
      - REGION=ap-south
    build:
      context: .
    ports:
      - "50002:5000"

  pyroscope:
    image: pyroscope/pyroscope
    environment:
      - PYROSCOPE_LOG_LEVEL=debug
    ports:
      - '4040:4040'
    command:
      - 'server'

  prometheus:
    image: prom/prometheus:latest
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:11.3.0
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
    depends_on:
      - us-east
      - eu-north
      - ap-south
      - pyroscope
      - prometheus